title: ryanlaycock
contentDir: ../../../../www/html/
header:
  socials:
    - url: https://github.com/ryanlaycock
      icon: fa fa-github
    - url: https://www.linkedin.com/in/ryan-laycock-038489183
      icon: fa fa-linkedin
    - url: https://twitter.com/mynameisryan98
      icon: fa fa-twitter
    - url: https://www.instagram.com/mynameisryan98/
      icon: fa fa-instagram
  links:
    - url: /projects
      name: Projects
    - url: /cooking
      name: Cooking

content:
  /projects:
    name: Projects
    staticURL: static_content/projects.html
    children:
      /rpi-screen:
        name: RPi Screen
        githubProject: ryanlaycock/rpi-screen
        filePath: README.md
        children:
            /rpi-screen-setup:
                name: RPi Screen Setup
                githubProject: ryanlaycock/rpi-screen
                filePath: setup/rpisetup.md
      /hello-world:
        name: Hello World!
        githubProject: ryanlaycock/ryanlaycock.uk
        filePath: content/hello_world/index.md
  /cooking:
    name: Cooking
    children:
      /mozzy:
        name: Mozzy
        githubProject: hendricius/mozzarella
        filePath: README.md
