title: ryanlaycock
contentDir: ../../../../www/html/
header:
  socials:
    - url: https://github.com/ryanlaycock
      icon: fa fa-github
    - url: https://www.linkedin.com/in/ryan-laycock-038489183
      icon: fa fa-linkedin
    - url: https://twitter.com/mynameisryan98
      icon: fa fa-twitter
    - url: https://www.instagram.com/mynameisryan98/
      icon: fa fa-instagram
  links:
    - url: /projects
      name: Projects
    - url: /cooking
      name: Cooking

content:
  /:
    name: ryanlaycock.uk
    githubProject: ryanlaycock/ryanlaycock.uk
    filePath: content/home/index.md
    pinnedPostsHeader: Pinned Posts
    pinnedPosts:
      - /projects/hello-world
      - /projects/rpi-screen
      - /projects/rpi-screen/rpi-screen-setup
      - /cooking/mozzy
  /projects:
    name: Projects
    childrenHeader: Projects
    children:
      /rpi-screen:
        name: RPi Screen
        githubProject: ryanlaycock/rpi-screen
        filePath: README.md
        description: Turning a 16x16 RGB matrix into a PC monitor
        date: "2021-01-01"
        displayChildren: true
        children:
            /rpi-screen-setup:
                name: RPi Screen Setup
                githubProject: ryanlaycock/rpi-screen
                filePath: setup/rpisetup.md
                description: Setting up the rpi-screen.
                date: "2021-01-01"
      /hello-world:
        name: Hello World! 👋
        githubProject: ryanlaycock/ryanlaycock.uk
        filePath: content/hello_world/index.md
        description: Hello world! My first post here, and what better to write about than making this website itself.
        date: "2023-03-11"
        children:
          /example:
            name: Example
            githubProject: ryanlaycock/ryanlaycock.uk
            filePath: content/hello_world/example/index.md
            date: "2021-01-01"
  /cooking:
    name: Cooking
    childrenHeader: Cooking Recipes
    children:
      /mozzy:
        name: Mozzy
        githubProject: hendricius/mozzarella
        filePath: README.md
        description: Some radomm website for making mozzarella lol
        date: "2021-01-01"
