# This is a basic workflow to help you get started with Actions

name: deploy-main

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Maybe build things here?
        run: echo TODO Maybe build things here?

      # From https://github.com/dogweather/raspberry-pi-python-github-runner/blob/main/.github/workflows/python-test-in-cloud.yml
      - name: Set up Python in a virtual env
        run: |
          if [[ `uname` != "Darwin" ]]; then sudo apt -y install python3-venv; fi
          python3 -m venv .env

      - name: Install dependencies
        run: |
          source .env/bin/activate
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Runs a set of commands using the runners shell
      - name: Run generate_content.py 
        run: |
          source .env/bin/activate
          python3 generate_content.py
